RecipeFormatVersion: '2020-01-25'
ComponentName: 'com.shishido.PhysicalVerification'
ComponentVersion: 'GITHUB_RUN_NUMBER'
ComponentDescription: 'Physical GPIO Verification Component'
ComponentPublisher: 'Shishido'
ComponentDependencies:
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ">=2.0.0"
    DependencyType: "HARD"
Manifests:
  - Platform:
      os: linux
    Artifacts:
      - URI: 's3://iot-test-pipe/artifacts/main.py'
    Lifecycle:
      Run: 'python3 {artifacts:path}/main.py'